FROM maven:3.6.3-openjdk-11 AS build
COPY ./ /app
WORKDIR /app
RUN mvn --show-version --update-snapshots --batch-mode clean package

FROM adoptopenjdk:11-jre-hotspot
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/basketball-events-api/target/basketball-events-api-1.0.0.jar /app
EXPOSE 8080
CMD ["java", "-jar", "basketball-events-api-1.0.0.jar"]