kumuluzee:
  name: basketball-events
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/EventsDS
      connection-url: jdbc:postgresql://pg-events.clvqrwayazxs.eu-central-1.rds.amazonaws.com/events
      username: postgres
      password: postgres12
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/EventsDS
  metrics:
    web-instrumentation:
      - name: events-endpoint
        url-pattern: /v1/events/*
  rest-client:
    registrations:
      - class: events-api
        url: http://localhost:8080/v1
        read-timeout: 5000
  config:
    consul:
      agent: http://localhost:8500

rest-config:
  maintenance-mode: false
  api-token: htn12kss3
